// web/src/pages/OverviewPage.tsx
import { useQuery } from "@tanstack/react-query";
import {
  AlertCircle,
  ArrowDownToLine,
  ArrowUpFromLine,
  CheckCircle2,
  RefreshCw,
  WalletCards,
} from "lucide-react";
import { useMemo, useState } from "react";
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import {
  apiRequest,
  type Schemas,
  type TransactionOut,
} from "../api/client";
import { RefundDrawer } from "../components/RefundDrawer";
import { TransactionTable } from "../components/TransactionTable";
import {
  ErrorState,
  IconButton,
  LoadingState,
  StatusMark,
  formatMoney,
  formatTime,
} from "../components/ui";

type OverviewData = {
  transactions: Schemas["PaginatedTransactionOut"];
  wallets: Schemas["PaginatedWalletOut"];
  devices: Schemas["PaginatedDeviceOut"];
  daily: Schemas["DailyReportOut"];
  reconciliation: Schemas["ReconciliationReportOut"];
  offline: Schemas["OfflineReviewItemOut"][];
  deliveries: Schemas["PaginatedWebhookDeliveryOut"];
};

async function loadOverview(): Promise<OverviewData> {
  const [
    transactions,
    wallets,
    devices,
    daily,
    reconciliation,
    offline,
    deliveries,
  ] = await Promise.all([
    apiRequest<Schemas["PaginatedTransactionOut"]>(
      "/admin/api/v1/transactions?page=1&limit=10",
    ),
    apiRequest<Schemas["PaginatedWalletOut"]>("/admin/api/v1/wallets?page=1&limit=100"),
    apiRequest<Schemas["PaginatedDeviceOut"]>("/admin/api/v1/devices?page=1&limit=8"),
    apiRequest<Schemas["DailyReportOut"]>("/admin/api/v1/reports/daily"),
    apiRequest<Schemas["ReconciliationReportOut"]>(
      "/admin/api/v1/ledger/reconciliation",
    ),
    apiRequest<Schemas["OfflineReviewItemOut"][]>("/admin/api/v1/offline/review"),
    apiRequest<Schemas["PaginatedWebhookDeliveryOut"]>(
      "/admin/api/v1/webhooks/deliveries?page=1&limit=5",
    ),
  ]);
  return {
    transactions,
    wallets,
    devices,
    daily,
    reconciliation,
    offline,
    deliveries,
  };
}

export function OverviewPage() {
  const overview = useQuery({ queryKey: ["overview"], queryFn: loadOverview });
  const [refundTransaction, setRefundTransaction] =
    useState<TransactionOut | null>(null);

  const derived = useMemo(() => {
    if (!overview.data) return null;
    const currency =
      overview.data.wallets.items[0]?.currency ??
      overview.data.daily.currency ??
      "USD";
    const liability = overview.data.wallets.items.reduce(
      (total, wallet) => total + wallet.balance_minor,
      0,
    );
    const latestDay = overview.data.daily.rows.at(-1);
    const chart = overview.data.daily.rows.slice(-14).map((row) => ({
      day: new Date(`${row.day}T00:00:00`).toLocaleDateString(undefined, {
        month: "short",
        day: "numeric",
      }),
      load: row.total_credit_minor / 100,
      spend: row.total_debit_minor / 100,
    }));
    const reconciliationCount = overview.data.reconciliation.issues.length;
    return { currency, liability, latestDay, chart, reconciliationCount };
  }, [overview.data]);

  if (overview.isLoading) return <LoadingState label="Loading operations overview" />;
  if (overview.error || !overview.data || !derived) {
    return (
      <ErrorState
        message={overview.error?.message ?? "Overview is unavailable"}
        retry={() => overview.refetch()}
      />
    );
  }

  const failedDeliveries = overview.data.deliveries.items.filter(
    (delivery) => !["success", "pending"].includes(delivery.status),
  );

  return (
    <div className="overview-page">
      <section className="metric-band" aria-label="Financial status">
        <Metric
          label="Wallet liability"
          value={formatMoney(derived.liability, derived.currency)}
          detail={`${overview.data.wallets.total} active wallet records`}
          icon={WalletCards}
          tone="neutral"
        />
        <Metric
          label="Today's load"
          value={formatMoney(
            derived.latestDay?.total_credit_minor ?? 0,
            derived.currency,
          )}
          detail={`${derived.latestDay?.transaction_count ?? 0} transactions`}
          icon={ArrowDownToLine}
          tone="positive"
        />
        <Metric
          label="Today's spend"
          value={formatMoney(
            derived.latestDay?.total_debit_minor ?? 0,
            derived.currency,
          )}
          detail="Posted debit volume"
          icon={ArrowUpFromLine}
          tone="positive"
        />
        <Metric
          label="Reconciliation"
          value={derived.reconciliationCount ? "Review required" : "Balanced"}
          detail={`${derived.reconciliationCount} differences`}
          icon={derived.reconciliationCount ? AlertCircle : CheckCircle2}
          tone={derived.reconciliationCount ? "warning" : "positive"}
        />
      </section>

      <div className="overview-grid">
        <section className="panel chart-panel">
          <header className="panel-header">
            <div>
              <h2>Transaction volume</h2>
              <p>Daily posted value</p>
            </div>
            <div className="chart-legend">
              <span className="legend-load">Load</span>
              <span className="legend-spend">Spend</span>
            </div>
          </header>
          <div className="chart-area">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={derived.chart}>
                <CartesianGrid stroke="#e6e8eb" strokeDasharray="3 3" />
                <XAxis dataKey="day" tickLine={false} axisLine={false} />
                <YAxis tickLine={false} axisLine={false} width={48} />
                <Tooltip
                  formatter={(value) =>
                    new Intl.NumberFormat(undefined, {
                      style: "currency",
                      currency: derived.currency,
                    }).format(Number(value))
                  }
                />
                <Line
                  type="monotone"
                  dataKey="load"
                  stroke="#2457d6"
                  strokeWidth={2}
                  dot={false}
                />
                <Line
                  type="monotone"
                  dataKey="spend"
                  stroke="#16833b"
                  strokeWidth={2}
                  dot={false}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </section>

        <section className="panel exceptions-panel">
          <header className="panel-header">
            <div>
              <h2>Operational exceptions</h2>
              <p>Queues that need attention</p>
            </div>
            <IconButton
              label="Refresh exceptions"
              icon={RefreshCw}
              onClick={() => overview.refetch()}
            />
          </header>
          <ExceptionGroup
            title="Offline review"
            count={overview.data.offline.length}
            rows={overview.data.offline.slice(0, 3).map((item) => ({
              primary: `Sequence ${item.sequence_number}`,
              secondary: `${formatMoney(item.amount_minor)} / ${item.card_uid}`,
              status: item.status,
            }))}
          />
          <ExceptionGroup
            title="Failed webhooks"
            count={failedDeliveries.length}
            rows={failedDeliveries.slice(0, 3).map((delivery) => ({
              primary: delivery.event_type,
              secondary: `${delivery.attempts} attempts / ${formatTime(
                delivery.next_retry_at,
              )}`,
              status: delivery.status,
            }))}
          />
        </section>

        <section className="panel recent-panel">
          <header className="panel-header">
            <div>
              <h2>Recent transactions</h2>
              <p>Newest posted activity</p>
            </div>
          </header>
          <TransactionTable
            transactions={overview.data.transactions.items}
            onRefund={setRefundTransaction}
          />
        </section>

        <section className="panel device-panel">
          <header className="panel-header">
            <div>
              <h2>Device health</h2>
              <p>Latest registered state</p>
            </div>
          </header>
          <div className="compact-list">
            {overview.data.devices.items.map((device) => (
              <div key={device.id}>
                <span>
                  <strong>{device.name}</strong>
                  <small>{device.type}</small>
                </span>
                <StatusMark value={device.status} />
              </div>
            ))}
          </div>
        </section>
      </div>
      <RefundDrawer
        transaction={refundTransaction}
        onClose={() => setRefundTransaction(null)}
      />
    </div>
  );
}

function Metric({
  label,
  value,
  detail,
  icon: Icon,
  tone,
}: {
  label: string;
  value: string;
  detail: string;
  icon: typeof WalletCards;
  tone: "neutral" | "positive" | "warning";
}) {
  return (
    <div className={`metric metric-${tone}`}>
      <span>
        <small>{label}</small>
        <strong>{value}</strong>
        <em>{detail}</em>
      </span>
      <Icon aria-hidden="true" size={23} />
    </div>
  );
}

function ExceptionGroup({
  title,
  count,
  rows,
}: {
  title: string;
  count: number;
  rows: { primary: string; secondary: string; status: string }[];
}) {
  return (
    <div className="exception-group">
      <h3>
        {title} <span>{count}</span>
      </h3>
      {rows.length ? (
        rows.map((row, index) => (
          <div className="exception-row" key={`${row.primary}-${index}`}>
            <span>
              <strong>{row.primary}</strong>
              <small>{row.secondary}</small>
            </span>
            <StatusMark value={row.status} />
          </div>
        ))
      ) : (
        <p className="clear-queue">No items waiting.</p>
      )}
    </div>
  );
}

// web/src/pages/OverviewPage.vue
<script setup lang="ts">
import {
  RiAlertLine,
  RiCheckboxCircleLine,
  RiDownload2Line,
  RiRefreshLine,
  RiUpload2Line,
  RiWallet3Line,
} from "@remixicon/vue";
import { useQuery } from "@tanstack/vue-query";
import { computed, ref, type Component } from "vue";

import { apiRequest, type Schemas, type TransactionOut } from "../api/client";
import DataState from "../components/DataState.vue";
import IconButton from "../components/IconButton.vue";
import OverviewChart from "../components/OverviewChart.vue";
import RefundDrawer from "../components/RefundDrawer.vue";
import StatusMark from "../components/StatusMark.vue";
import TransactionTable from "../components/TransactionTable.vue";
import { formatMoney, formatTime } from "../utils/format";

type OverviewData = {
  transactions: Schemas["PaginatedTransactionOut"];
  wallets: Schemas["PaginatedWalletOut"];
  devices: Schemas["PaginatedDeviceOut"];
  daily: Schemas["DailyReportOut"];
  reconciliation: Schemas["ReconciliationReportOut"];
  offline: Schemas["OfflineReviewItemOut"][];
  deliveries: Schemas["PaginatedWebhookDeliveryOut"];
};

async function loadOverview(): Promise<OverviewData> {
  const [transactions, wallets, devices, daily, reconciliation, offline, deliveries] =
    await Promise.all([
      apiRequest<Schemas["PaginatedTransactionOut"]>(
        "/admin/api/v1/transactions?page=1&limit=10",
      ),
      apiRequest<Schemas["PaginatedWalletOut"]>(
        "/admin/api/v1/wallets?page=1&limit=100",
      ),
      apiRequest<Schemas["PaginatedDeviceOut"]>(
        "/admin/api/v1/devices?page=1&limit=8",
      ),
      apiRequest<Schemas["DailyReportOut"]>("/admin/api/v1/reports/daily"),
      apiRequest<Schemas["ReconciliationReportOut"]>(
        "/admin/api/v1/ledger/reconciliation",
      ),
      apiRequest<Schemas["OfflineReviewItemOut"][]>("/admin/api/v1/offline/review"),
      apiRequest<Schemas["PaginatedWebhookDeliveryOut"]>(
        "/admin/api/v1/webhooks/deliveries?page=1&limit=5",
      ),
    ]);
  return { transactions, wallets, devices, daily, reconciliation, offline, deliveries };
}

const overview = useQuery({ queryKey: ["overview"], queryFn: loadOverview });
const refundTransaction = ref<TransactionOut | null>(null);
const derived = computed(() => {
  if (!overview.data.value) return null;
  const data = overview.data.value;
  const currency = data.wallets.items[0]?.currency ?? data.daily.currency ?? "USD";
  const liability = data.wallets.items.reduce(
    (total, wallet) => total + wallet.balance_minor,
    0,
  );
  const latestDay = data.daily.rows.at(-1);
  const chart = data.daily.rows.slice(-14).map((row) => ({
    day: new Date(`${row.day}T00:00:00`).toLocaleDateString(undefined, {
      month: "short",
      day: "numeric",
    }),
    load: row.total_credit_minor / 100,
    spend: row.total_debit_minor / 100,
  }));
  return {
    currency,
    liability,
    latestDay,
    chart,
    reconciliationCount: data.reconciliation.issues.length,
  };
});
const failedDeliveries = computed(() =>
  (overview.data.value?.deliveries.items ?? []).filter(
    (delivery) => !["success", "pending"].includes(delivery.status),
  ),
);
const metrics = computed<
  { label: string; value: string; detail: string; icon: Component; tone: string }[]
>(() => {
  if (!overview.data.value || !derived.value) return [];
  return [
    {
      label: "Wallet liability",
      value: formatMoney(derived.value.liability, derived.value.currency),
      detail: `${overview.data.value.wallets.total} active wallet records`,
      icon: RiWallet3Line,
      tone: "text-primary",
    },
    {
      label: "Today's load",
      value: formatMoney(
        derived.value.latestDay?.total_credit_minor ?? 0,
        derived.value.currency,
      ),
      detail: `${derived.value.latestDay?.transaction_count ?? 0} transactions`,
      icon: RiDownload2Line,
      tone: "text-success",
    },
    {
      label: "Today's spend",
      value: formatMoney(
        derived.value.latestDay?.total_debit_minor ?? 0,
        derived.value.currency,
      ),
      detail: "Posted debit volume",
      icon: RiUpload2Line,
      tone: "text-success",
    },
    {
      label: "Reconciliation",
      value: derived.value.reconciliationCount ? "Review required" : "Balanced",
      detail: `${derived.value.reconciliationCount} differences`,
      icon: derived.value.reconciliationCount ? RiAlertLine : RiCheckboxCircleLine,
      tone: derived.value.reconciliationCount ? "text-warning" : "text-success",
    },
  ];
});
</script>

<template>
  <DataState
    v-if="overview.isLoading.value"
    message="Loading operations overview"
  />
  <DataState
    v-else-if="overview.error.value || !overview.data.value || !derived"
    kind="error"
    :message="overview.error.value?.message ?? 'Overview is unavailable'"
    retry
    @retry="overview.refetch()"
  />
  <div v-else>
    <section
      class="-mx-[22px] -mt-[18px] mb-4 grid min-h-[112px] grid-cols-4 border-b border-line bg-white px-[22px] max-[1120px]:grid-cols-2 max-[760px]:-mx-3 max-[760px]:-mt-4 max-[760px]:mb-3 max-[760px]:grid-cols-1 max-[760px]:px-3"
      aria-label="Financial status"
    >
      <div
        v-for="metric in metrics"
        :key="metric.label"
        class="flex min-w-0 items-start justify-between border-r border-line px-5 py-5 first:pl-1 last:border-r-0 max-[1120px]:nth-[2]:border-r-0 max-[1120px]:nth-[-n+2]:border-b max-[760px]:min-h-[88px] max-[760px]:border-r-0 max-[760px]:border-b max-[760px]:px-1 max-[760px]:py-3.5"
      >
        <span class="grid min-w-0 gap-1">
          <small class="text-[11px] text-muted">{{ metric.label }}</small>
          <strong class="truncate text-xl font-bold tracking-[-0.02em] max-[760px]:text-lg">{{ metric.value }}</strong>
          <em class="text-[10px] not-italic text-muted">{{ metric.detail }}</em>
        </span>
        <component :is="metric.icon" aria-hidden="true" class="size-[23px] shrink-0" :class="metric.tone" />
      </div>
    </section>

    <div class="grid grid-cols-[minmax(0,2.2fr)_minmax(280px,.95fr)] gap-3 max-[1120px]:grid-cols-1">
      <section class="h-[342px] overflow-hidden rounded-md border border-line bg-white max-[760px]:h-[300px]">
        <header class="flex min-h-14 items-center justify-between border-b border-line px-3.5 py-2.5">
          <div>
            <h2 class="text-[13px] font-bold">Transaction volume</h2>
            <p class="mt-0.5 text-[10px] text-muted">Daily posted value</p>
          </div>
          <div class="flex gap-4 text-[10px] text-muted">
            <span class="flex items-center gap-1.5 before:h-0.5 before:w-4 before:bg-primary">Load</span>
            <span class="flex items-center gap-1.5 before:h-0.5 before:w-4 before:bg-success">Spend</span>
          </div>
        </header>
        <div class="h-[284px] p-3.5 max-[760px]:h-[236px]">
          <OverviewChart :rows="derived.chart" :currency="derived.currency" />
        </div>
      </section>

      <section class="min-h-[342px] overflow-hidden rounded-md border border-line bg-white max-[1120px]:min-h-0">
        <header class="flex min-h-14 items-center justify-between border-b border-line px-3.5 py-2.5">
          <div>
            <h2 class="text-[13px] font-bold">Operational exceptions</h2>
            <p class="mt-0.5 text-[10px] text-muted">Queues that need attention</p>
          </div>
          <IconButton label="Refresh exceptions" :icon="RiRefreshLine" @click="overview.refetch()" />
        </header>
        <div class="border-b border-line p-3.5">
          <h3 class="mb-3 text-[11px] font-bold">Offline review <span class="ml-1 rounded border border-[#e7b957] bg-warning-soft px-1.5 py-0.5 text-warning">{{ overview.data.value.offline.length }}</span></h3>
          <div v-if="overview.data.value.offline.length" class="grid gap-2">
            <div v-for="item in overview.data.value.offline.slice(0, 3)" :key="item.id" class="flex items-center justify-between gap-2">
              <span class="grid"><strong class="text-[11px]">Sequence {{ item.sequence_number }}</strong><small class="text-[9px] text-muted">{{ formatMoney(item.amount_minor) }} / {{ item.card_uid }}</small></span>
              <StatusMark :value="item.status" />
            </div>
          </div>
          <p v-else class="py-2 text-[10px] text-muted">No items waiting.</p>
        </div>
        <div class="p-3.5">
          <h3 class="mb-3 text-[11px] font-bold">Failed webhooks <span class="ml-1 rounded border border-[#e7b957] bg-warning-soft px-1.5 py-0.5 text-warning">{{ failedDeliveries.length }}</span></h3>
          <div v-if="failedDeliveries.length" class="grid gap-2">
            <div v-for="delivery in failedDeliveries.slice(0, 3)" :key="delivery.id" class="flex items-center justify-between gap-2">
              <span class="grid"><strong class="text-[11px]">{{ delivery.event_type }}</strong><small class="text-[9px] text-muted">{{ delivery.attempts }} attempts / {{ formatTime(delivery.next_retry_at) }}</small></span>
              <StatusMark :value="delivery.status" />
            </div>
          </div>
          <p v-else class="py-2 text-[10px] text-muted">No items waiting.</p>
        </div>
      </section>

      <section class="min-h-[220px] overflow-hidden rounded-md border border-line bg-white max-[760px]:min-h-0">
        <header class="min-h-14 border-b border-line px-3.5 py-2.5">
          <h2 class="text-[13px] font-bold">Recent transactions</h2>
          <p class="mt-0.5 text-[10px] text-muted">Newest posted activity</p>
        </header>
        <TransactionTable
          :transactions="overview.data.value.transactions.items"
          refundable
          @refund="refundTransaction = $event"
        />
      </section>

      <section class="min-h-[220px] overflow-hidden rounded-md border border-line bg-white max-[1120px]:min-h-0">
        <header class="min-h-14 border-b border-line px-3.5 py-2.5">
          <h2 class="text-[13px] font-bold">Device health</h2>
          <p class="mt-0.5 text-[10px] text-muted">Latest registered state</p>
        </header>
        <div>
          <div v-for="device in overview.data.value.devices.items" :key="device.id" class="flex min-h-12 items-center justify-between border-b border-line px-3.5 py-2 last:border-b-0">
            <span class="grid"><strong class="text-[11px]">{{ device.name }}</strong><small class="text-[9px] text-muted">{{ device.type }}</small></span>
            <StatusMark :value="device.status" />
          </div>
        </div>
      </section>
    </div>
    <RefundDrawer :transaction="refundTransaction" @close="refundTransaction = null" />
  </div>
</template>
