// web/src/components/AppShell.vue
<script setup lang="ts">
import {
  RiArrowDownSLine,
  RiBankCardLine,
  RiBuilding2Line,
  RiCloseLine,
  RiDashboardLine,
  RiFileList3Line,
  RiGroupLine,
  RiHistoryLine,
  RiKey2Line,
  RiMenuLine,
  RiNotificationLine,
  RiRfidLine,
  RiSettings3Line,
  RiWallet3Line,
  RiWebhookLine,
  RiWifiOffLine,
} from "@remixicon/vue";
import { computed, ref } from "vue";
import { useRoute } from "vue-router";

import { useAuth } from "../auth/useAuth";
import IconButton from "./IconButton.vue";

const navigation = [
  { to: "/", label: "Overview", icon: RiDashboardLine },
  { to: "/customers", label: "Customers", icon: RiGroupLine, permission: "customers:read" },
  { to: "/cards", label: "Cards", icon: RiBankCardLine, permission: "cards:read" },
  { to: "/wallets", label: "Wallets", icon: RiWallet3Line, permission: "wallets:read" },
  {
    to: "/transactions",
    label: "Transactions",
    icon: RiHistoryLine,
    permission: "transactions:read",
  },
  { to: "/devices", label: "Devices", icon: RiRfidLine, permission: "devices:read" },
  {
    to: "/offline",
    label: "Offline review",
    icon: RiWifiOffLine,
    permission: "transactions:read",
  },
  {
    to: "/webhooks",
    label: "Webhooks",
    icon: RiWebhookLine,
    permission: "integrations:manage",
  },
  {
    to: "/api-keys",
    label: "API keys",
    icon: RiKey2Line,
    permission: "integrations:manage",
  },
  { to: "/audit", label: "Audit log", icon: RiFileList3Line, permission: "audit:read" },
  {
    to: "/settings",
    label: "Settings",
    icon: RiSettings3Line,
    permission: "settings:manage",
  },
];

const route = useRoute();
const { user, permissions, logout } = useAuth();
const mobileNav = ref(false);
const current = computed(
  () =>
    navigation.find((item) =>
      item.to === "/" ? route.path === "/" : route.path.startsWith(item.to),
    ) ?? navigation[0],
);
const visibleNavigation = computed(() =>
  navigation.filter((item) => !item.permission || permissions.value.has(item.permission)),
);
</script>

<template>
  <div class="min-h-screen bg-subtle md:grid md:grid-cols-[216px_minmax(0,1fr)]">
    <button
      v-if="mobileNav"
      class="fixed inset-0 z-30 border-0 bg-black/25 md:hidden"
      aria-label="Close navigation"
      @click="mobileNav = false"
    />
    <aside
      class="fixed inset-y-0 left-0 z-40 flex w-[min(280px,86vw)] -translate-x-full flex-col bg-sidebar text-white transition-transform duration-200 md:sticky md:top-0 md:h-screen md:w-auto md:translate-x-0"
      :class="mobileNav ? 'translate-x-0 shadow-[10px_0_30px_rgb(20_24_28/24%)]' : ''"
    >
      <div class="flex h-16 shrink-0 items-center gap-2.5 px-[18px] text-[15px] font-extrabold tracking-[0.04em]">
        <span class="grid size-7 place-items-center rounded-md bg-primary text-[13px]" aria-hidden="true">C</span>
        <span>CASPRA</span>
        <IconButton
          label="Close navigation"
          :icon="RiCloseLine"
          class="ml-auto border-sidebar-raised bg-transparent text-white md:hidden"
          @click="mobileNav = false"
        />
      </div>
      <nav class="grid gap-0.5 px-2.5 py-3" aria-label="Primary navigation">
        <RouterLink
          v-for="item in visibleNavigation"
          :key="item.to"
          :to="item.to"
          class="flex h-10 items-center gap-3 rounded-md border-l-[3px] border-transparent px-2.5 text-[12px] font-semibold text-[#d8dde1] transition-colors hover:bg-sidebar-raised hover:text-white"
          active-class="!border-primary !bg-sidebar-raised !text-white"
          :exact-active-class="item.to === '/' ? '!border-primary !bg-sidebar-raised !text-white' : ''"
          @click="mobileNav = false"
        >
          <component :is="item.icon" aria-hidden="true" class="size-[19px] shrink-0" />
          <span>{{ item.label }}</span>
        </RouterLink>
      </nav>
      <div class="mt-auto flex items-center gap-2 border-t border-sidebar-raised px-[18px] py-5 text-[10px] text-[#d8dde1]">
        <span class="size-2 rounded-full bg-[#21b34b]" aria-hidden="true" />
        All systems operational
      </div>
    </aside>

    <div class="min-w-0">
      <header class="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-line bg-white px-[22px] max-[760px]:h-14 max-[760px]:px-2.5">
        <div class="flex items-center gap-3">
          <span class="hidden max-[760px]:block">
            <IconButton
              label="Open navigation"
              :icon="RiMenuLine"
              @click="mobileNav = true"
            />
          </span>
          <h2 class="text-lg font-bold tracking-[-0.02em] max-[760px]:text-base">{{ current.label }}</h2>
        </div>
        <div class="flex items-center gap-2">
          <button
            class="flex h-9 items-center gap-2 rounded-md border border-line bg-white px-3 text-[11px] text-ink max-[760px]:hidden"
            title="Current organization"
          >
            <RiBuilding2Line aria-hidden="true" class="size-4" />
            <span>Primary venue</span>
            <RiArrowDownSLine aria-hidden="true" class="size-[15px]" />
          </button>
          <IconButton label="Notifications" :icon="RiNotificationLine" class="max-[760px]:hidden" />
          <button
            class="flex h-10 min-w-[210px] items-center gap-2.5 rounded-md border border-line bg-white px-2.5 text-left max-[760px]:min-w-0 max-[760px]:border-0 max-[760px]:px-1"
            @click="logout"
          >
            <span class="grid size-7 shrink-0 place-items-center rounded-full bg-[#45515c] text-[11px] font-bold text-white">
              {{ user?.email.slice(0, 1).toUpperCase() }}
            </span>
            <span class="grid min-w-0 flex-1 max-[760px]:hidden">
              <strong class="truncate text-[11px] leading-4">{{ user?.full_name || "Operator" }}</strong>
              <small class="truncate text-[9px] leading-3 text-muted">{{ user?.email }}</small>
            </span>
            <RiArrowDownSLine aria-hidden="true" class="size-[15px] max-[760px]:hidden" />
          </button>
        </div>
      </header>
      <main class="min-h-[calc(100vh-64px)] p-[18px_22px_32px] max-[760px]:min-h-[calc(100vh-56px)] max-[760px]:p-4 max-[760px]:px-3">
        <RouterView />
      </main>
    </div>
  </div>
</template>

// web/src/components/AppShell.tsx
import {
  Bell,
  Building2,
  ChevronDown,
  CircleGauge,
  CreditCard,
  FileKey2,
  History,
  Menu,
  RadioTower,
  ScrollText,
  Settings,
  Users,
  WalletCards,
  Webhook,
  WifiOff,
  X,
} from "lucide-react";
import { useState } from "react";
import { NavLink, Outlet, useLocation } from "react-router-dom";

import { useAuth } from "../auth/AuthProvider";
import { IconButton } from "./ui";

const navigation = [
  { to: "/", label: "Overview", icon: CircleGauge },
  {
    to: "/customers",
    label: "Customers",
    icon: Users,
    permission: "customers:read",
  },
  { to: "/cards", label: "Cards", icon: CreditCard, permission: "cards:read" },
  {
    to: "/wallets",
    label: "Wallets",
    icon: WalletCards,
    permission: "wallets:read",
  },
  {
    to: "/transactions",
    label: "Transactions",
    icon: History,
    permission: "transactions:read",
  },
  {
    to: "/devices",
    label: "Devices",
    icon: RadioTower,
    permission: "devices:read",
  },
  {
    to: "/offline",
    label: "Offline review",
    icon: WifiOff,
    permission: "transactions:read",
  },
  {
    to: "/webhooks",
    label: "Webhooks",
    icon: Webhook,
    permission: "integrations:manage",
  },
  {
    to: "/api-keys",
    label: "API keys",
    icon: FileKey2,
    permission: "integrations:manage",
  },
  {
    to: "/audit",
    label: "Audit log",
    icon: ScrollText,
    permission: "audit:read",
  },
  {
    to: "/settings",
    label: "Settings",
    icon: Settings,
    permission: "settings:manage",
  },
];

export function AppShell() {
  const { user, permissions, logout } = useAuth();
  const [mobileNav, setMobileNav] = useState(false);
  const location = useLocation();
  const current =
    navigation.find((item) =>
      item.to === "/" ? location.pathname === "/" : location.pathname.startsWith(item.to),
    ) ?? navigation[0];
  const visibleNavigation = navigation.filter(
    (item) => !item.permission || permissions.has(item.permission),
  );

  return (
    <div className="app-shell">
      <aside className={`sidebar ${mobileNav ? "sidebar-open" : ""}`}>
        <div className="brand-row">
          <span className="brand-mark" aria-hidden="true">
            C
          </span>
          <span>CASPRA</span>
          <IconButton
            label="Close navigation"
            icon={X}
            className="mobile-close"
            onClick={() => setMobileNav(false)}
          />
        </div>
        <nav aria-label="Primary navigation">
          {visibleNavigation.map(({ to, label, icon: Icon }) => (
            <NavLink
              key={to}
              to={to}
              end={to === "/"}
              onClick={() => setMobileNav(false)}
            >
              <Icon aria-hidden="true" size={19} />
              <span>{label}</span>
            </NavLink>
          ))}
        </nav>
        <div className="system-status">
          <span aria-hidden="true" />
          All systems operational
        </div>
      </aside>

      <div className="workspace">
        <header className="topbar">
          <div className="topbar-title">
            <IconButton
              label="Open navigation"
              icon={Menu}
              className="mobile-menu"
              onClick={() => setMobileNav(true)}
            />
            <h2>{current.label}</h2>
          </div>
          <div className="topbar-actions">
            <button className="venue-selector" title="Current organization">
              <Building2 aria-hidden="true" size={16} />
              <span>Primary venue</span>
              <ChevronDown aria-hidden="true" size={15} />
            </button>
            <IconButton label="Notifications" icon={Bell} />
            <button className="operator-menu" onClick={logout}>
              <span className="operator-avatar">
                {user?.email.slice(0, 1).toUpperCase()}
              </span>
              <span>
                <strong>{user?.full_name || "Operator"}</strong>
                <small>{user?.email}</small>
              </span>
              <ChevronDown aria-hidden="true" size={15} />
            </button>
          </div>
        </header>
        <main className="main-content">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
